tap (#1)

diff --git a/run-examples b/run-examples
--- a/run-examples
+++ b/run-examples
@@ -1,21 +1,22 @@
 #!/bin/bash -e
+
 for i in examples/*; do
   printf "$i..."
-  mocha --require . $i > /dev/null
+  tap --node-arg=-r . $i > /dev/null
   ecode=$?
   if [[ $i == *"failing"* ]] || [[ $i == *"explosive"* ]] ||
-      [[ $i == *"explode"* ]] || [[ $i == *"returns-promise"* ]]; then
-    if [[ $ecode == 0 ]]; then
-      echo "Failure: $i"
-      echo "Expected exitcode != 0, but saw $ecode"
-      exit 1
-    fi
-  else
-    if [[ $ecode != 0 ]]; then
-      echo "Failure: $i"
-      echo "Expected exitcode == 0, but saw $ecode"
-      exit 1
-    fi
+    [[ $i == *"explode"* ]] || [[ $i == *"returns-promise"* ]]; then
+  if [[ $ecode == 0 ]]; then
+    echo "Failure: $i"
+    echo "Expected exitcode != 0, but saw $ecode"
+    exit 1
   fi
-  printf " ok\n"
+else
+  if [[ $ecode != 0 ]]; then
+    echo "Failure: $i"
+    echo "Expected exitcode == 0, but saw $ecode"
+    exit 1
+  fi
+fi
+printf " ok\n"
 done
